CREATE DATABASE ReleyeDb;
USE ReleyeDb;

CREATE TABLE Addresses (
    AddressID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Country NVARCHAR(50) NOT NULL,
    City NVARCHAR(50) NOT NULL,
    Street NVARCHAR(100) NULL,
    ZipCode NVARCHAR(20) NULL
);

CREATE TABLE Customers (
    CustomerID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    CreatedAt DATETIME NOT NULL,
    AddressID UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_Customer_Address FOREIGN KEY (AddressID) REFERENCES Addresses(AddressID)
);
